name:    Robot Framework Tests

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up epoch timestamp
              id: epoch
              run: echo "EPOCH=$(date +%s)" >> $GITHUB_ENV
            
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.8'

            - name: Install dependencies
              run:  |
                 python -m pip install --upgrade pip
                 pip install -r requirements.txt

            - name: Run Robot Framework tests
              run:  robot -d results tests/

            - name: Archive test results
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: robot-test-results-${{ env.EPOCH }}
                path: results/

